# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the minecraft version (without the 1.)
loaderVersion="${neo_version}" #mandatory

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your
# redistributive properties. Review your options at https://choosealicense.com/. All rights
# reserved is the default copyright stance, and is thus the default here.
license="MIT" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="" #optional

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/mezz/ModNameTooltip/issues?q=is%3Aissue" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://curseforge.com/minecraft/mc-mods/mod-name-tooltip" #optional

# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional

# A text field displayed in the mod UI
#credits="Thanks for this example mod goes to Java" #optional

# A text field displayed in the mod UI
authors="mezz" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="modnametooltip" #mandatory

displayTest="IGNORE_ALL_VERSION"

# The version number of the mod
version="${mod_version}" #mandatory

# A display name for the mod
displayName="Mod Name Tooltip" #mandatory

# The description text for the mod (multi line!) (#mandatory)
description='''
On ItemStack tooltips, shows which mod the item is from.
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.modnametooltip]]
    modId="neoforge" #mandatory

    versionRange="${neo_version_range}" #mandatory
	# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
	ordering="NONE"
	# Side this dependency is applied on - BOTH, CLIENT or SERVER
	side="BOTH"

[[dependencies.modnametooltip]]
	modId="minecraft" #mandatory
	versionRange="[1.20.4,1.21)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="CLIENT"
